title: "Tech Bytes"
author: "Arun Samayam"
email: "samayamarun@gmail.com"
description: "Practical notes on software engineering, architecture, cloud, data, and AI."
url: "https://asamayam.github.io"

theme: minima

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    disable: false
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

markdown: kramdown
highlighter: rouge

permalink: /:categories/:year/:month/:day/:title/

github_username: asamayam
linkedin_username: arun-samayam
rss: rss

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      author: "Arun Samayam"
      tags: Technical